### ISSUE TITLE
upgrading to golang > 1.5.4 breaks lifecycler/systray operation on all versions of macOS

### ISSUE THREAD

**Issue by dkujawski** [AnimationMentor/systray#1]
Trying to use newer versions of golang to support latest macOS version 10.12.
When compiling with a version of golang larger than 1.5.4 the cgo code paths fail at runtime.

Seems that it could be related to this: 
https://golang.org/doc/go1.6#cgo

I have tried using go versions: 

- 1.6.3
- 1.6.4
- 1.7.3
- 1.7.4

As mentioned in the release notes, I did try turning off the checks with: `GODEBUG=cgocheck=0` 

Compile time warnings are present when compiling with 1.5.4 but does not seem to have a negative impact on operation when running on macOS versions older than 10.12.
```
src/github.com/AnimationMentor/systray/tray_darwin.c:200:23: warning: instance method '-showIcon:hint:' not found (return type defaults to 'id') [-Wobjc-method-access]
src/github.com/AnimationMentor/systray/tray_darwin.c:207:23: warning: instance method '-showIcon:hint:' not found (return type defaults to 'id') [-Wobjc-method-access]
src/github.com/AnimationMentor/systray/tray_darwin.c:214:23: warning: instance method '-addMenuItem:manager:index:enabled:checked:callback:' not found (return type defaults to 'id') [-Wobjc-method-access]
src/github.com/AnimationMentor/systray/tray_darwin.c:22
```
Running from the commandline with verbose logging returns:
```
$> ./lifecycler
I1208 11:43:29.149971   25013 main.go:164] Starting tray...
I1208 11:43:29.150077   25013 tray.go:103] Starting tray
I1208 11:43:29.150080   25013 launcher.go:40] Starting child process
I1208 11:43:29.150102   25013 tray.go:129] Setting tray icon: artella.ok.png ARTELLA
Running main loop on systray 0xc42008e1c0
I1208 11:43:29.152664   25013 tray.go:106] Exiting tray
I1208 11:43:29.152775   25013 main.go:115] launcherMsg: AppState:Starting
I1208 11:43:29.152783   25013 main.go:122] IS IDLE: false
I1208 11:43:29.149994   25013 updater.go:45] Starting updater
I1208 11:43:29.152941   25013 updater.go:54] Waiting for new versions to hit the release server...
```
Note the "Setting tray icon: artella.ok.png " and "Exiting tray" log lines which indicate that the tray_darwin.c code paths seem to be having trouble.

**Comment by dkujawski** [comment]
note that the tray.go files referenced in the log files above are not stored in this repo but in an offline svn repo.  the lines referenced are calling into the tray_darwin.c code that was compiled using cgo.

**Comment by reedwade** [comment]
I wish I had any helpful ideas.

Have you tried out the systray tests and examples to confirm they work in that environment?
